services:
  - type: web
    name: pharmasud-api
    runtime: python
    branch: master
    autoDeploy: true
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: pharmasud-db
          property: connectionString

databases:
  - name: pharmasud-db
    databaseName: pharmasud
    user: pharmasud
    plan: free